"""add_stripe_account_id_to_users

Revision ID: de0e576c7fee
Revises: 0afc0315b633
Create Date: 2026-05-09 21:53:11.701274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'de0e576c7fee'
down_revision: Union[str, None] = '0afc0315b633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_account_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stripe_account_id')
    # ### end Alembic commands ###
